### ISSUE TITLE
workflow update

### ISSUE THREAD

**Issue by relekang** [havardh/workflow#128]
It would be nice to be able to update all workflow packages in workflow home with a simple command.

```
$ workflow update
The following will be updated:
  · workflow-core          1.0.0 -> 1.1.0
  · workflow-app-chrome    1.0.1 -> 1.0.2
Are you sure? (y/N)
```

**Comment by havardh** [comment]
@relekang I've updated the description and title to match #89

**Comment by havardh** [comment]
Should we move to ~ dependencies and make this run `npm update` ?

And concerning packaging for this and future commands, we have a few options:
1. Implement this as part of `workflow-cmd`.
2. Implement this as `workflow-cmd-update` or `workflow-update` and call it from [`workflow`](https://github.com/havardh/workflow/blob/master/packages/workflow/src/cli.js#L15).
3. Implement this as `workflow-cmd-update` or `workflow-update` and call if from [`workflow-cmd`](https://github.com/havardh/workflow/blob/master/packages/workflow-cmd/src/cli.js#L12).

I'm leaning towards (3) and the possibility of extracting [`workflow-cmd/src/index`](https://github.com/havardh/workflow/blob/master/packages/workflow-cmd/src/index.js) into `workflow-cmd-apply`. Thus leaving the `workflow-cmd` with the responsibility of choosing the command and executing the appropriate package, defaulting to `apply`.

**Comment by relekang** [comment]
I don't understand what the benefits of separating workflow-cmd into different packages vs files in the workflow-cmd package. Can you elaborate?

**Comment by relekang** [comment]
> Should we move to ~ dependencies and make this run npm update ?

Don't think it will give us the overview and make it possible to ask the question. I was thinking, maybe see if we can use npm-check-updates or something like a library.
