### ISSUE TITLE
Add support for OSX

### ISSUE THREAD

**Issue by havardh** [havardh/workflow#3]
We want to support the OSX platform. 

As a first prototype using AppleScript is proposed.

**Comment by havardh** [comment]
Implemented using JXA (Javascript OSX automation) as part of #41.

**Comment by tiffon** [comment]
This project is sick. Great work!

**Comment by havardh** [comment]
@tiffon Thanks :D I'm glad that you like it. Feel free to let me know if you find bugs or missing or confusing features. The project is quite experimental, so there are still a lot of gaps.
