### ISSUE TITLE
Make workflow-apps-defaults read from actual workflow-home

### ISSUE THREAD

**Issue by havardh** [havardh/workflow#94]
The `workflow-apps-defaults` package reads user defaults from `~/.workflow/apps/defaults`. This should be read from `baseFolder` found in `shared/env`.

**Comment by relekang** [comment]
It would be really nice if browser was read from the default browser setting in the OS if it is not defined in workflow home.

**Comment by havardh** [comment]
@relekang: did you get any further on your investigations on making it read from OS settings? Or did you get stuck with the `async` issue. Could we solve it by relying on sync operations in this package?

**Comment by relekang** [comment]
We cannot do it sync without implementing our own bplist parser, and I would rather spend the time making a solution for async things.

**Comment by havardh** [comment]
@relekang The original bug was resolved in #118, please open a new issue for your proposed feature :+1:
